##===- proj/lib/Makefile -----------------------------------*- Makefile -*-===##

#
# This folder is specifically for dynamically loaded libraries.
# Most of the interesting stuff is in lib/Transforms.
# This was inherrited from the llvm/projects/sample.
#

#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#
DIRS=Transforms Analyses Tests

include $(LEVEL)/Makefile.common
