##===- proj/lib/Transforms/Makefile ------------------------*- Makefile -*-===##

#
# This folder holds all the source code for LLVM passes.
#

#
# Relative path to the top of the source tree.
#
LEVEL=../..

# Name of the library to build
LIBRARYNAME = Transforms

# # Make the shared library become a loadble module so the tools can
# # dlopen/dlsym on the resulting library.
LOADABLE_MODULE = 1

include $(LEVEL)/Makefile.common
